/*
* Automatically generated by 'ng g ng-alain:plugin icon'
*/

import {
  AlipayCircleOutline,
  AppstoreOutline,
  ArrowDownOutline,
  CopyrightOutline,
  DesktopOutline,
  FileMarkdownOutline,
  FormOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MinusSquareOutline,
  PlusSquareOutline,
  SettingOutline,
  TableOutline,
  TagsOutline,
  TaobaoCircleOutline,
  ToolOutline,
  UserOutline,
  WeiboCircleOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AlipayCircleOutline,
  AppstoreOutline,
  ArrowDownOutline,
  CopyrightOutline,
  DesktopOutline,
  FileMarkdownOutline,
  FormOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MinusSquareOutline,
  PlusSquareOutline,
  SettingOutline,
  TableOutline,
  TagsOutline,
  TaobaoCircleOutline,
  ToolOutline,
  UserOutline,
  WeiboCircleOutline
];
