import { MockRequest } from '@delon/mock';

const $columns = [
  {
    title: '编号',
    index: 'id',
    className: 'text-center',
    fixed: 'left',
    width: 60
  },
  {
    title: '状态',
    index: 'status',
    className: 'text-center',
    fixed: 'left',
    width: 60
  },
  {
    title: '名称',
    index: 'title',
    fixed: 'left',
    width: 240
  },
  {
    title: '表名',
    index: 'TABLE_NAME',
    fixed: 'left',
    width: 240
  },
  {
    title: '字段',
    index: 'status',
    fixed: 'left',
    width: 60
  },
  {
    title: '引擎',
    index: 'ENGINE',
    className: 'text-center',
    width: 96
  },
  {
    title: '版本',
    index: 'VERSION',
    className: 'text-center',
    width: 96
  },
  {
    title: '行格式',
    index: 'ROW_FORMAT',
    className: 'text-center',
    width: 96
  },
  {
    title: '数据行数',
    index: 'TABLE_ROWS',
    className: 'text-center',
    width: 96
  },
  {
    title: '行均长度',
    index: 'AVG_ROW_LENGTH',
    className: 'text-center',
    width: 96
  },
  {
    title: '数据长度',
    index: 'DATA_LENGTH',
    className: 'text-center',
    width: 96
  },
  {
    title: '索引长度',
    index: 'INDEX_LENGTH',
    className: 'text-center',
    width: 96
  },
  {
    title: '空间碎片',
    index: 'DATA_FREE',
    className: 'text-center',
    width: 96
  },
  {
    title: '主键自增值',
    index: 'AUTO_INCREMENT',
    className: 'text-center',
    width: 120
  },
  {
    title: '更新时间',
    index: 'UPDATE_TIME',
    type: 'date',
    dateFormat: 'yyyy-MM-dd',
    width: 120
  },
  {
    title: '检查时间',
    index: 'CHECK_TIME',
    type: 'date',
    dateFormat: 'yyyy-MM-dd',
    width: 120
  },
  {
    title: '编码集',
    index: 'TABLE_COLLATION',
    width: 120
  },
  {
    title: '校验和',
    index: 'CHECKSUM',
    width: 80
  },
  {
    title: '创建选项',
    index: 'CREATE_OPTIONS',
    width: 180
  },
  {
    title: '备注',
    index: 'TABLE_COMMENT',
    fixed: 'right',
    render: 'remark',
    width: 300
  }
];
const $data = {
  items: [
    {
      id: 1,
      title: 'API接口信息',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_api',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '221',
      AVG_ROW_LENGTH: '222',
      DATA_LENGTH: '49152',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '0',
      AUTO_INCREMENT: '222',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '接口地址'
    },
    {
      id: 2,
      title: '商圈（可能不能通用用）',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_business',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '21',
      AVG_ROW_LENGTH: '780',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '0',
      AUTO_INCREMENT: '25',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '商圈'
    },
    {
      id: 3,
      title: '行政划分（可能不能通用）',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_division',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '48747',
      AVG_ROW_LENGTH: '140',
      DATA_LENGTH: '6832128',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '2097152',
      AUTO_INCREMENT: null,
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '行政划分'
    },
    {
      id: 4,
      title: '文件管理',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_file',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '9',
      AVG_ROW_LENGTH: '5461',
      DATA_LENGTH: '49152',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '0',
      AUTO_INCREMENT: '33',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: '',
      TABLE_COMMENT: '部分字段可能适用于部分场景。\n如图片类型文件才会有宽高。'
    },
    {
      id: 5,
      title: '文件使用场景',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_file_scene',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '19',
      AVG_ROW_LENGTH: '862',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '0',
      AUTO_INCREMENT: '22',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: '',
      TABLE_COMMENT: ''
    },
    {
      id: 6,
      title: '表单配置',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_form',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '1',
      AVG_ROW_LENGTH: '16384',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '0',
      AUTO_INCREMENT: '2',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: '',
      TABLE_COMMENT: ''
    },
    {
      id: 7,
      title: '系统日志',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_log',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '535',
      AVG_ROW_LENGTH: '2970',
      DATA_LENGTH: '1589248',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '0',
      DATA_FREE: '2097152',
      AUTO_INCREMENT: '6495',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '系统日志'
    },
    {
      id: 8,
      title: '团队成员',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_member',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '7',
      AVG_ROW_LENGTH: '2340',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '49152',
      DATA_FREE: '0',
      AUTO_INCREMENT: '40',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '团队成员'
    },
    {
      id: 9,
      title: '团队成员关联的职位',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_member_post',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '6',
      AVG_ROW_LENGTH: '2730',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '49152',
      DATA_FREE: '0',
      AUTO_INCREMENT: '19',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '成员授权职位'
    },
    {
      id: 10,
      title: '团队成员关联的角色',
      status: 1,
      TABLE_CATALOG: 'def',
      TABLE_SCHEMA: 'rmt_manager',
      TABLE_NAME: 'bs_system_member_role',
      TABLE_TYPE: 'BASE TABLE',
      ENGINE: 'InnoDB',
      VERSION: '10',
      ROW_FORMAT: 'Dynamic',
      TABLE_ROWS: '9',
      AVG_ROW_LENGTH: '1820',
      DATA_LENGTH: '16384',
      MAX_DATA_LENGTH: '0',
      INDEX_LENGTH: '16384',
      DATA_FREE: '0',
      AUTO_INCREMENT: '109',
      CREATE_TIME: '2022-11-22 03:26:02',
      UPDATE_TIME: null,
      CHECK_TIME: null,
      TABLE_COLLATION: 'utf8mb4_general_ci',
      CHECKSUM: null,
      CREATE_OPTIONS: 'row_format=DYNAMIC',
      TABLE_COMMENT: '成员授权角色'
    }
  ],
  page: {
    totalCount: 26,
    pageCount: 3,
    currentPage: 1,
    perPage: 10
  }
};

export const COLUMN_SCHEMA = {
  '/table/column': (req: MockRequest) => $columns,
  '/table/data': (req: MockRequest) => $data
};
